spring.application.name=presencia-disponibilidad-service

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/presencia_disponibilidad_db?createDatabaseIfNotExist=true&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true